import { ReadOnlyObjectArray } from "./ReadOnlyObjectArray";

/**
 * Tuple generated by arrayFilterTuple, which contains matching and non matching
 * values.
 *
 * @template Item Type of the items being filtered.
 * @template Filtered Type of the matching items.
 */
export type FilterTuple<Item, Filtered extends Item = Item> = readonly [
	matching: ReadOnlyObjectArray<Filtered>,
	nonMatching: ReadOnlyObjectArray<
		Exclude<Item, Filtered> extends never
			? Filtered
			: Exclude<Item, Filtered>
	>
];

export default FilterTuple;
