import type { OptionalExclude } from "./OptionalExclude";

/**
 * Tuple generated by arrayFilterTuple, which contains matching and non matching
 * values.
 *
 * @template Item Type of the items being filtered.
 * @template Filtered Type of the matching items.
 */
export type FilterTuple<Item, Filtered extends Item = Item> = readonly [
	filteredIn: ReadonlyArray<Filtered>,
	filteredOut: ReadonlyArray<OptionalExclude<Item, Filtered>>
];
